"use client";
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { useEffect,useLayoutEffect,useRef } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import type {SceneState} from './Scene';
import Clocks from './Clocks';
import {useReducedMotion} from '../MotionPreference';
import PlayfulStatus from '../PlayfulStatus';
import './landing.css';
const Scene=dynamic(()=>import('./Scene'),{ssr:false,loading:()=> <div className="scene" aria-hidden><div className="scene-fallback"/></div>});
gsap.registerPlugin(ScrollTrigger);
export type LandingData={projects:{id:string;name:string;description:string;stack:string[]}[];posts:{slug:string;title:string;excerpt:string;date:string}[];photos:{id:string;image:string;caption:string}[];available:boolean};
export default function Landing({projects,posts,photos,available}:LandingData){const reduced=useReducedMotion();const ref=useRef<HTMLDivElement>(null);const state=useRef<SceneState>({progress:0,paused:false});
useEffect(()=>{document.body.classList.add('on-landing');return()=>{document.body.classList.remove('on-landing');delete document.body.dataset.chapter;};},[]);
useLayoutEffect(()=>{const ctx=gsap.context(()=>{const sections=gsap.utils.toArray<HTMLElement>('.landing-chapter');sections.forEach((section,index)=>{ScrollTrigger.create({trigger:section,start:'top 100px',end:'bottom 100px',onToggle:self=>{if(self.isActive)document.body.dataset.chapter=section.id;}});ScrollTrigger.create({trigger:section,start:'top top',end:'bottom top',onUpdate:self=>{if(self.isActive||index===0&&self.progress===0){state.current.progress=Math.min(4,index+self.progress);window.dispatchEvent(new Event('scenechange'));}}});});if(!reduced)gsap.fromTo('.hero-copy > *',{opacity:0,y:16},{opacity:1,y:0,stagger:.09,duration:.85,ease:'power3.out',clearProps:'opacity,transform'});},ref);return()=>ctx.revert();},[reduced]);
return <div ref={ref} className={`landing ${reduced?'motion-quiet':''}`}><Scene state={state} reduced={reduced}/><div className="scene-shade" aria-hidden/>
<section className="landing-chapter landing-hero" id="home"><div className="landing-content hero-content"><div className="hero-copy"><h1>I’m Kathan.</h1><p className="hero-lead">I’m a founder of <a href="https://bugbase.in" target="_blank" rel="noreferrer">BugBase</a>.<br/>In San Francisco, building AI for security.</p><p className="hero-aside">I also write, take photographs,<br/>and make things for the fun of it.</p></div><div className="hero-bottom"><Link href="https://copilot.bugbase.ai" target="_blank" rel="noreferrer" className="current-project"><span>Currently building</span><strong>Pentest Copilot <span aria-hidden>↗</span></strong></Link><PlayfulStatus/></div></div></section>
<section className="landing-chapter" id="building"><div className="landing-content landing-split"><div className="landing-intro"><h2>Things I’m<br/>building.</h2><p>BugBase is the main thing.<br/>The rest usually starts as a question I can’t leave alone.</p><Link className="landing-link" href="/projects">All projects →</Link></div><div className="landing-projects">{projects.map(p=><article key={p.id}><h3><Link href={`/projects/${p.id}`}>{p.name} <span aria-hidden>↗</span></Link></h3><p>{p.description}</p>{p.stack.length>0&&<small>{p.stack.slice(0,4).join(' · ')}</small>}</article>)}{projects.length===0&&<p>{available?'More projects are on their way.':'Projects are temporarily unavailable.'} <Link href="/projects">Visit projects</Link></p>}</div></div></section>
<section className="landing-chapter" id="writing"><div className="landing-content landing-split"><div className="landing-intro"><h2>Writing<br/>things down.</h2><p>Build notes, security,<br/>and ideas I want to work through.</p><Link className="landing-link" href="/blogs">All writing →</Link></div><div className="landing-essays">{posts.map(p=><Link key={p.slug} href={`/blogs/${p.slug}`}><small>{p.date}</small><h3>{p.title}</h3><span>Read the essay ↗</span></Link>)}{posts.length===0&&<p>{available?'More writing is on its way.':'Writing is temporarily unavailable.'} <Link href="/blogs">Visit writing</Link></p>}</div></div></section>
<section className="landing-chapter landing-photography" id="photographs"><div className="landing-content photo-content"><div className="photo-heading"><div><h2>Away from<br/>the keyboard.</h2><p>A few things I stopped to look at.</p></div><Link className="text-link" href="/photography">The complete gallery →</Link></div><div className="landing-photo-strip">{photos.map(p=><Link key={p.id} href={`/photography?photo=${p.id}`}><img src={p.image} alt={p.caption||'Photograph by Kathan Desai'} loading="lazy"/><span>{p.caption}</span></Link>)}</div>{photos.length===0&&<p className="photo-empty">{available?'More photographs are on their way.':'The gallery is temporarily unavailable.'}</p>}</div></section>
<section className="landing-chapter landing-about" id="about"><div className="landing-content landing-about-content"><div><h2>From Delhi.<br/>In San Francisco, for now.</h2><p>I grew up in Delhi, left college at 20, and started BugBase with friends. What began as a Discord server in a dorm room became the company I’m building today.</p><p>I like making useful things, asking too many questions, and occasionally getting far enough from a screen to notice where I am.</p><div className="about-links"><Link href="/about">More about me →</Link><Link href="/work">My work →</Link></div></div><figure><img src="/kathan.JPG" alt="Kathan outdoors in Los Angeles" loading="lazy"/><figcaption>Sometimes, outside.</figcaption></figure></div></section><div className="landing-clocks"><Clocks reduced={reduced}/></div></div>;
}
